[[Sundials]]
arch = "aarch64"
git-tree-sha1 = "9a548aba93a9f8fe35530046ae36e3a4f47321f2"
libgfortran_version = "5.0.0"
os = "macos"

    [[Sundials.download]]
    sha256 = "807f1fdc75931acff9263fc1cef565b9a8ac8d377c32e6b3e931c9ca7d5a8b8c"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.5.1+0/Sundials.v6.5.1.aarch64-apple-darwin-libgfortran5.tar.gz"
[[Sundials]]
arch = "aarch64"
git-tree-sha1 = "ba6ba666e9ea8d1bae72f8fef688398cf025c448"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "602097d5c76d406db21e56642e6982a082e31b2ced27bb0252fb6e559ece38de"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.5.1+0/Sundials.v6.5.1.aarch64-linux-gnu-libgfortran3.tar.gz"
[[Sundials]]
arch = "aarch64"
git-tree-sha1 = "dc88aff4dfc199b59ada67cd80083dde2af35caf"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "dd955d099e2ec82ec4a5434c1f691b8d5091dc82cf7e793560f7c192c68ab772"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.5.1+0/Sundials.v6.5.1.aarch64-linux-gnu-libgfortran4.tar.gz"
[[Sundials]]
arch = "aarch64"
git-tree-sha1 = "730a8a5bb82ba56b3b7922912480db1130de919b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "00f3889048ba6860ff3b4479a44be69fb20877ab794bd132b70c696513647158"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.5.1+0/Sundials.v6.5.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[Sundials]]
arch = "aarch64"
git-tree-sha1 = "4d32d0532ec289d2320219f80dcb5b173fcf4830"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "b24130f2cac9f842c767e1360bec77f20066eff5237801ccaed30feb7af4855a"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.5.1+0/Sundials.v6.5.1.aarch64-linux-musl-libgfortran3.tar.gz"
[[Sundials]]
arch = "aarch64"
git-tree-sha1 = "f7cd5ea3452dc79b1c051336f2bd1523394bbd2a"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "f8c63462cf99eeab069b84223d0cfdeba50e49149ba7d85d77f5444a994fcd9e"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.5.1+0/Sundials.v6.5.1.aarch64-linux-musl-libgfortran4.tar.gz"
[[Sundials]]
arch = "aarch64"
git-tree-sha1 = "ce729728a5a679196666d9ae34aefbe2771dbd5a"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "57cbc861b548eb2761316a2390d7cd7655c5e48735eb9085b8cbbdb9d02aa351"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.5.1+0/Sundials.v6.5.1.aarch64-linux-musl-libgfortran5.tar.gz"
[[Sundials]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fcc8d69fda99a2a9900e74e85e6d47b90f99c459"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "ea741ff7b93ff7e58625ca5f5a88e5bb15ff890ccaf4bc18ea4186844b3c4d0c"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.5.1+0/Sundials.v6.5.1.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[Sundials]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "61505f6e8b08fa9d5de99c101e88c20a9741da8d"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "ca77af7e319f3eba06acaa89202d99c297105e3eac9030570c287520f4b3bc65"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.5.1+0/Sundials.v6.5.1.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[Sundials]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "03a419a2a73bb144602b6af2ba5303748ef661d1"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "295776837d2f822c62463ccc6eea32b002104b2b9e0fdba7b428e443dbf83afb"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.5.1+0/Sundials.v6.5.1.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[Sundials]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "81b70e32a6dc934aa798ab89dea406d7d664feb7"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "23cc415b0c66dcfcd8fed62ac896a8c6427f7fa34348bbc01ab156616a67457f"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.5.1+0/Sundials.v6.5.1.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[Sundials]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2e9298fdcf91abc6bc6678fe56b192e8b6095417"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "aff6f5708279446a58133fd8f469a6e52210c2f80fcecc543a06e54f0bfe8de7"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.5.1+0/Sundials.v6.5.1.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[Sundials]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5f16993a9b44511e8c1fb93b759a5aeacf5297a2"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "d6ab5ef90cf69f871ec40122d4beca8b54a3501ce8e9e5dc99a097843c6970c4"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.5.1+0/Sundials.v6.5.1.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[Sundials]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b351ccb6120ad1468dc87c89e8ec8a2847badac7"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "5c2000689f8ffc3dedc4389c5f4d095da824d52f3ed126cf5202783cf93dd471"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.5.1+0/Sundials.v6.5.1.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[Sundials]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "be12ded3735600c957347b395decb96a4b8a0427"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "8b405e6b96e2df22fa5c9460845abe70a6bad7019f47eb03d4ce9d4ceff0dc2b"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.5.1+0/Sundials.v6.5.1.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[Sundials]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9de49c85268a70c5e541fd6f77ea2032483ad70a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "588814f567f9dd8281ff8c4a2fb9dd8e8f7cb286a64a0212086213b175fc4e44"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.5.1+0/Sundials.v6.5.1.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[Sundials]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "67eed5d7ab4cf4eba918aeb2c46636f86543c9f1"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "20597ed48f26adcad8d2e56f5306d70ef3c42e192cba3315613d6cc19cd9b221"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.5.1+0/Sundials.v6.5.1.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[Sundials]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "30839626426608384786b56fe6ca82607ae23153"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "e9638c61cd27a362b77bfb7541300516dde8a1d4bf07982082abf4df3fd213e1"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.5.1+0/Sundials.v6.5.1.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[Sundials]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9bd1c1c7ab1c1330fe4d8a73adec3ebef5a168e3"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "c3b88ef8630f0ca86c2748032d309f94c9f7c321ddf87e5b8ea767430408057e"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.5.1+0/Sundials.v6.5.1.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "4f5c59a129bba589d3844f27e6f3f27d747357f1"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "10a9bc90ad8297aaa5a01f47fe32ca0cb23f13e974522fbed9f3ea717740d3c7"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.5.1+0/Sundials.v6.5.1.i686-linux-gnu-libgfortran3.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "437cc623c4b67700a90f794b5682f7533bad9c7f"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "1207eb4d2c47a9756738e643fcdc8d694916dd375925b1722338d86f7f27259d"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.5.1+0/Sundials.v6.5.1.i686-linux-gnu-libgfortran4.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "6af6e60948542090857643c98248024f31a125df"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "3e0405be623c872959b8d080e0f435f6639baba6a27946130f825774d7e75726"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.5.1+0/Sundials.v6.5.1.i686-linux-gnu-libgfortran5.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "5c95f19e40d97dbff911d130fe07d39710beff0a"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "524b5e0c9c1e80b24ffed6c8f729e966ff46110002ebd0ef951bb3a5b0f755d3"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.5.1+0/Sundials.v6.5.1.i686-linux-musl-libgfortran3.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "093e6ce83b2d194356512519963888af5699a286"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "8be2416a8828e45122c07034c19350d5412fd45334ec12b07de8e2722eb75bcb"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.5.1+0/Sundials.v6.5.1.i686-linux-musl-libgfortran4.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "4360332781fe994c0715cc466ea3d49befe35488"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "9d64e331484f63e996bef5c45a186de4d5bc8f7fe4db104c0f321bd46b09959e"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.5.1+0/Sundials.v6.5.1.i686-linux-musl-libgfortran5.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "4e5bf9de1b4c925387a02b5fec96e8dcee0345b5"
libgfortran_version = "3.0.0"
os = "windows"

    [[Sundials.download]]
    sha256 = "0f89ae0697c4ce8e5c67ac90ceeedd530cfcc44dc67b07cc3dd1a919c24f5e0e"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.5.1+0/Sundials.v6.5.1.i686-w64-mingw32-libgfortran3.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "86e20ad6e549796361e01aca32fb938dbf5893f8"
libgfortran_version = "4.0.0"
os = "windows"

    [[Sundials.download]]
    sha256 = "cc402d820bd98cebc9edfebf0a648dc1d261a4b07563aa99c5e672531602aa8c"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.5.1+0/Sundials.v6.5.1.i686-w64-mingw32-libgfortran4.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "fc772eaea76206df9a14307dd684b6f155c58b36"
libgfortran_version = "5.0.0"
os = "windows"

    [[Sundials.download]]
    sha256 = "60b0203e1099a31bfc523b109bc40f205826253d6400097e94599477eff1222c"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.5.1+0/Sundials.v6.5.1.i686-w64-mingw32-libgfortran5.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "533d05bf1c28c4da7725a74e67f17f177d505aca"
libgfortran_version = "3.0.0"
os = "macos"

    [[Sundials.download]]
    sha256 = "1729015c3799784806ec756d92be626fc740e2ce62b768f815acd9c7ed32bdba"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.5.1+0/Sundials.v6.5.1.x86_64-apple-darwin-libgfortran3.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "533d05bf1c28c4da7725a74e67f17f177d505aca"
libgfortran_version = "4.0.0"
os = "macos"

    [[Sundials.download]]
    sha256 = "1729015c3799784806ec756d92be626fc740e2ce62b768f815acd9c7ed32bdba"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.5.1+0/Sundials.v6.5.1.x86_64-apple-darwin-libgfortran4.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "533d05bf1c28c4da7725a74e67f17f177d505aca"
libgfortran_version = "5.0.0"
os = "macos"

    [[Sundials.download]]
    sha256 = "1729015c3799784806ec756d92be626fc740e2ce62b768f815acd9c7ed32bdba"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.5.1+0/Sundials.v6.5.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "ddcbd94379e365de170f0488c0ca7b643051de73"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "497d188cf8c54be17860bd86627935b2660a7f931dac7d8939e8b1e172fee398"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.5.1+0/Sundials.v6.5.1.x86_64-linux-gnu-libgfortran3.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "dc0990bf9db3a392ea685b16768c173dadbd7507"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "15e25fa6f1b13e7600a399cc1574dfbb2e1c9413e361e0c9087ab9964f7300cb"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.5.1+0/Sundials.v6.5.1.x86_64-linux-gnu-libgfortran4.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "961adb27df4aa7a5a95a2e35c0245d7f9c87402d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "a4a8e63d24c5e57c0b22c56bbec452273418124f13878d61ca39a6e10547ef95"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.5.1+0/Sundials.v6.5.1.x86_64-linux-gnu-libgfortran5.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "e54c82e280886fadcad7ac02b9a6ade97e7f0b02"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "9c31801af6cff56c668518d6af1d62e9a2def398d8e0e3953d801fe48fc4a773"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.5.1+0/Sundials.v6.5.1.x86_64-linux-musl-libgfortran3.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "da7e91f8798cbd2f7bbb779c235d6514ef31dc4a"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "fff0ca5cfd547209010c86733e7f1d739b1e47970d86eddcf823c944d8eff621"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.5.1+0/Sundials.v6.5.1.x86_64-linux-musl-libgfortran4.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "a81c44275e54ed4042120d6a95a10b5b044237f5"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "19f8a779925ae676b44cdb2dc8901b7a58f1d6486847f439daede8e5a22bfc4c"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.5.1+0/Sundials.v6.5.1.x86_64-linux-musl-libgfortran5.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "9b76bad806acc4d3956b640a8cf01ccdf959bc08"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[Sundials.download]]
    sha256 = "dd852f6a8ef5cbd32f3d914e2237b447169b563f171413f5e14caf5ff46c1031"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.5.1+0/Sundials.v6.5.1.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "fc8a30072351879d70d267f02c31916aa04e2756"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[Sundials.download]]
    sha256 = "014e26401c4389819e59e1ebd8a950806b1ceb485d6869f5fc0d946e83e25f8d"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.5.1+0/Sundials.v6.5.1.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "d89b82cc127f70bfcf2d341cc3ffa420e3d1afd7"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Sundials.download]]
    sha256 = "1982b788a2cda6878e366fb8f10cec62039d271939ac0b190fc86dd23b17bc05"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.5.1+0/Sundials.v6.5.1.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "0e3badf5ad0c521006cdd1ae8e4b9557a76433fc"
libgfortran_version = "3.0.0"
os = "windows"

    [[Sundials.download]]
    sha256 = "78e6805c5a6d3b97b882e7e30c9a3b05e3d2894c3ed6496e39e5583aa1709bd9"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.5.1+0/Sundials.v6.5.1.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "9077ac37909e9047423fb0ac049dd256dcd53ae6"
libgfortran_version = "4.0.0"
os = "windows"

    [[Sundials.download]]
    sha256 = "6f6b0bf02812aa083802443a313bceaa41756cdaf890b2b94353bc83c539de7b"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.5.1+0/Sundials.v6.5.1.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "4ed658f7abf7b4d8df1b3e370d71e46f9e8fb090"
libgfortran_version = "5.0.0"
os = "windows"

    [[Sundials.download]]
    sha256 = "77c2319258919ad53957cf265e562c7dd4e18dc17884c910569c3ffa149eeac8"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.5.1+0/Sundials.v6.5.1.x86_64-w64-mingw32-libgfortran5.tar.gz"
