[[Sundials]]
arch = "aarch64"
git-tree-sha1 = "37cdd6cadef9e326a973fdd9711c8d7eb2046059"
libgfortran_version = "5.0.0"
os = "macos"

    [[Sundials.download]]
    sha256 = "aff610ddc619419bc1b0e37ef6a914ef51d3bb117c4d692a1c31b64e03ce7cbb"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v5.2.2+0/Sundials.v5.2.2.aarch64-apple-darwin-libgfortran5.tar.gz"
[[Sundials]]
arch = "aarch64"
git-tree-sha1 = "3cc3897045fe00c54709b9f52c12a18a3ee371a1"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "3c875bddba1e1f58f0c4689de859054a14eb4d7ccd73d8a4afdfd4dd44c68145"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v5.2.2+0/Sundials.v5.2.2.aarch64-linux-gnu-libgfortran3.tar.gz"
[[Sundials]]
arch = "aarch64"
git-tree-sha1 = "7eb80e0c1a7033180b95505d158326fdf2f17432"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "50b80f5533de8c9b9a9b3730a1360e6d2653e10f2e32bc2174a2bfae1b5e316e"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v5.2.2+0/Sundials.v5.2.2.aarch64-linux-gnu-libgfortran4.tar.gz"
[[Sundials]]
arch = "aarch64"
git-tree-sha1 = "c2942ffa649945f43bb8ac0c4068acbb856b85d1"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "f88aa9f871a6f5a3cf76bac1d7db41223e1bddef7b90c5cb016e9fbf6d690c09"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v5.2.2+0/Sundials.v5.2.2.aarch64-linux-gnu-libgfortran5.tar.gz"
[[Sundials]]
arch = "aarch64"
git-tree-sha1 = "32236b17ed3c1354062ab90bad79bdf57e9bc5a5"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "0ab7d312ecc24d2e41983b78ddcdd200598032547aca56456e1383a89d4f75ec"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v5.2.2+0/Sundials.v5.2.2.aarch64-linux-musl-libgfortran3.tar.gz"
[[Sundials]]
arch = "aarch64"
git-tree-sha1 = "e03df7bca8c53a487c10bd0d89425da96436d1d3"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "2fef206d5d8ee000e45fc10a1d223b7e5de5560bbaca3fc61fa70f0ad1bd7a47"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v5.2.2+0/Sundials.v5.2.2.aarch64-linux-musl-libgfortran4.tar.gz"
[[Sundials]]
arch = "aarch64"
git-tree-sha1 = "bbdb1c99c0671cb448e1dc5000429b69741be94a"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "b6f5237fee8636ae2d40c551d6c159029c5d8eb805b1f1fb4346051c728c5791"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v5.2.2+0/Sundials.v5.2.2.aarch64-linux-musl-libgfortran5.tar.gz"
[[Sundials]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d1fff23808be48701d69065fcefabdd9a897ba75"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "7f977cfc5cc3288a743be4e61ceacacb5be767a2b0bbdb984eb8b13b134c119d"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v5.2.2+0/Sundials.v5.2.2.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[Sundials]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bf22e7cb2aa1a93fd251be91d4e6ec35c2e159c8"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "c450440ce83edf7cf4bfdc5bf83f7b9560183882a2041ba1819085508183331a"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v5.2.2+0/Sundials.v5.2.2.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[Sundials]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "00bd7dabf67d5bed6580b9abd65e2fdebe22f06c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "1725901a88a40753a2c84140a5b98537a7006cc32d7c1d4ab75bb8f9065d9af2"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v5.2.2+0/Sundials.v5.2.2.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[Sundials]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "14b119c8748eb431e81ee4ebe4b128f82dd448b8"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "b45cfbb43ed7e7c97a1cf52f3d06050c62aa8c166887a0aba339d866f4e4c8b2"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v5.2.2+0/Sundials.v5.2.2.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[Sundials]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "12fae3c00e42e4b13215e1b9b32f36e7d5c58622"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "ee77873c3ed1a5ec310c19cd46d0ff0ee295b3236293090af7334380cdeb8f0c"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v5.2.2+0/Sundials.v5.2.2.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[Sundials]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f8b26a283e9e06c7903fc62950ee00c27afdd12c"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "cba50c0d000ee72a85768b895d9057b538ba33e2a73e174e301b3343824c8582"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v5.2.2+0/Sundials.v5.2.2.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[Sundials]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9434bfd3ded4e41b4bd1770e74446fd4d43eef74"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "176205761a51be6605d1ee4b79d6e9d055c982387314ceeb92d8bf6bce22319a"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v5.2.2+0/Sundials.v5.2.2.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[Sundials]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "45705c3aaecf7e9a433f130e2a3ae51d096e68ca"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "5099d9c4939cf5931f176f262cada7a8561d95986f779340e168587e5736595a"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v5.2.2+0/Sundials.v5.2.2.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[Sundials]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "eb174833aacaf6a9616993c27db1b81d60c5d4a6"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "9193289d682a470036eb0577746a6a9491da49140a8b99efbc11c525cac5bee4"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v5.2.2+0/Sundials.v5.2.2.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[Sundials]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e0f231c44b0448113593a59f691bbf8db83eada5"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "fc7b94f55104438dedfa8700e9ca640d07c2dff5cb545b2140dd244bf8f07688"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v5.2.2+0/Sundials.v5.2.2.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[Sundials]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3d1f32611b30ea472ee0490dabf10e05cd76d74c"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "ef576c5766513a3cba74efb3030f68a42322ee390e538a0b8180173d15d581e2"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v5.2.2+0/Sundials.v5.2.2.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[Sundials]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "31c9aae213566300f9ff5c7eb1c3a38ddc1be586"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "dae6c30ce2e752e067cdfc0042d046d8ffce4a5aa68ae7629d6d1a37c4d6b6cc"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v5.2.2+0/Sundials.v5.2.2.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "c68bbcd8d5d2f983550df237cb524ffa73e3dab9"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "72453c7824f35d7d29a03aac1f2c6186c11b54f7f455bbf3d054ca8177d9edfb"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v5.2.2+0/Sundials.v5.2.2.i686-linux-gnu-libgfortran3.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "e067b9353a81c20956b096c7eb75ae581d6b6ebc"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "4a4bc2a05053420b242349b4b227f686f0ad9bc8fe35139f8baeb7242ae85386"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v5.2.2+0/Sundials.v5.2.2.i686-linux-gnu-libgfortran4.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "23bd653ceec1c23c569c3e6ea02058f938358f23"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "5006b7ab99f7c0995d642deb99f46b25adf8a5c53e80ddb3d9b086d47c85ff3e"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v5.2.2+0/Sundials.v5.2.2.i686-linux-gnu-libgfortran5.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "fcb649f5a330fb7773350eab37899e4156dbe290"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "00e1856ff90433086cb8e2015cdcd89c4dbb050c9a4106a6f7336e6b88638971"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v5.2.2+0/Sundials.v5.2.2.i686-linux-musl-libgfortran3.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "885c0d56c7db50b3b244adf6fe7091659554e249"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "3db0bf9e64d9dc96bb95155c6fb1f2e8a45712f8936c262a5a7f7d07e4a1472e"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v5.2.2+0/Sundials.v5.2.2.i686-linux-musl-libgfortran4.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "fd418bbca7068425407040634635f4b69c9172dd"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "b71cb38d3c0fb18695ce95d798660eec30aa6a7202b58110609e792c632edd00"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v5.2.2+0/Sundials.v5.2.2.i686-linux-musl-libgfortran5.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "798d952fcc6841ee654a5b8e9ca5d96d4ecbe25f"
libgfortran_version = "3.0.0"
os = "windows"

    [[Sundials.download]]
    sha256 = "a0f92c85c790b33877f8393852a4e58e4b17fa2e1da90627e0fd4594f4bcf5a2"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v5.2.2+0/Sundials.v5.2.2.i686-w64-mingw32-libgfortran3.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "6b0c3ed83bd647b5fe5ea611f8a17eec90cff65c"
libgfortran_version = "4.0.0"
os = "windows"

    [[Sundials.download]]
    sha256 = "e89e3b23e4ba7e01d7b0f7197dde6b844188396ed90694b094c1ed7e43def022"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v5.2.2+0/Sundials.v5.2.2.i686-w64-mingw32-libgfortran4.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "7cfb5b36eedbf65c7cccbafc2b38b4d1cef49451"
libgfortran_version = "5.0.0"
os = "windows"

    [[Sundials.download]]
    sha256 = "75952da3e05c84688d60f2f79d25a6b0f6c6f59873eee9ae5e1002c0ad2d6f12"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v5.2.2+0/Sundials.v5.2.2.i686-w64-mingw32-libgfortran5.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "675a6e898219e89d68ffc69b8b8a2fcb74bf1be3"
libgfortran_version = "3.0.0"
os = "macos"

    [[Sundials.download]]
    sha256 = "568091e31e4874983557f0f824aab18dfe78fa206ed852ebf6f3d23ba8cfd8c0"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v5.2.2+0/Sundials.v5.2.2.x86_64-apple-darwin-libgfortran3.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "675a6e898219e89d68ffc69b8b8a2fcb74bf1be3"
libgfortran_version = "4.0.0"
os = "macos"

    [[Sundials.download]]
    sha256 = "568091e31e4874983557f0f824aab18dfe78fa206ed852ebf6f3d23ba8cfd8c0"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v5.2.2+0/Sundials.v5.2.2.x86_64-apple-darwin-libgfortran4.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "675a6e898219e89d68ffc69b8b8a2fcb74bf1be3"
libgfortran_version = "5.0.0"
os = "macos"

    [[Sundials.download]]
    sha256 = "568091e31e4874983557f0f824aab18dfe78fa206ed852ebf6f3d23ba8cfd8c0"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v5.2.2+0/Sundials.v5.2.2.x86_64-apple-darwin-libgfortran5.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "c6f487b04dfe1ae5b8b3a524d39680dd0e01888d"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "37d1366bb3b70a5bf5b01b6ecf6e1aaae3da985b43b8b2611affe1578aa7bc43"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v5.2.2+0/Sundials.v5.2.2.x86_64-linux-gnu-libgfortran3.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "146db86b771df60584c7f30a4f7b376049002eb1"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "8f312677ed23393bcd82e52e72bbeabce6d116d427f4afcbff688047eedd25d2"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v5.2.2+0/Sundials.v5.2.2.x86_64-linux-gnu-libgfortran4.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "1e35a1caa2beb6ae8e54b88f719e5ae6891c4dcc"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "874275676f62ed4a6a21f90102629a220eb3cc903649784354c096c7135f88ca"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v5.2.2+0/Sundials.v5.2.2.x86_64-linux-gnu-libgfortran5.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "8f56ebb024b7a84181735436b4e41d536fab0e64"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "56ffa7806fa62eaa2e77e18abbc12dbc9e944f4eab88797020a4d18680b1614b"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v5.2.2+0/Sundials.v5.2.2.x86_64-linux-musl-libgfortran3.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "22d1c1f17c3249b5d128968c504e45abe78f2ff0"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "394df7082e49d911aedc12f423f01e95ebd65e1cbd3f62836edd688d16ec1067"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v5.2.2+0/Sundials.v5.2.2.x86_64-linux-musl-libgfortran4.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "c051566a507c061c3752a6ab31160be73c7bcef5"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "add5183a111fb6a242b39b3f2ddf124f80ced98d9a91db4588fc0a730541445e"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v5.2.2+0/Sundials.v5.2.2.x86_64-linux-musl-libgfortran5.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "000831fb24d0c2641cfca4f9fd3431fb95e69c0d"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[Sundials.download]]
    sha256 = "473bacebff8b63fc16323190d8068b08c03ead0df70009e81ce1fa74b539ffdd"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v5.2.2+0/Sundials.v5.2.2.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "0bf8a235284f6ea4624d0559fb80489cab905ef4"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[Sundials.download]]
    sha256 = "974be1607587b5b800448013b4e5bb1f6cb7080a0fd0db7512f1a2536de80882"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v5.2.2+0/Sundials.v5.2.2.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "79e2a4c41b2bad77d8fa5de3543d4fd5ce522ff3"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Sundials.download]]
    sha256 = "89bca6a1e40bc98ace314cd0f6e5c420c86a67e9af202fb2c76f936c5ec3dfb1"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v5.2.2+0/Sundials.v5.2.2.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "db1b770364be5775abdfa647f9c3f1f8d6bcd2d7"
libgfortran_version = "3.0.0"
os = "windows"

    [[Sundials.download]]
    sha256 = "26eeb0d1e2864467ab286466940fc31508194ad92500c4635c03191dd062d875"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v5.2.2+0/Sundials.v5.2.2.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "615fa7ff3710c83b05a288b48a80377241868df3"
libgfortran_version = "4.0.0"
os = "windows"

    [[Sundials.download]]
    sha256 = "45315e5267b573e7fd56ac7b0c44a89a5c5c5591f701c9921798b57eb6b89d3b"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v5.2.2+0/Sundials.v5.2.2.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "89e2de680927805ce1a0b46b9ca742383fa224e7"
libgfortran_version = "5.0.0"
os = "windows"

    [[Sundials.download]]
    sha256 = "11d4bb261227a4b39f3109e881366e0e3404e25b273c35d5775467cdc74b1aec"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v5.2.2+0/Sundials.v5.2.2.x86_64-w64-mingw32-libgfortran5.tar.gz"
