[[Sundials]]
arch = "aarch64"
git-tree-sha1 = "c909fbf2c404287dc6a205f410b2e51a342b564c"
libc = "musl"
os = "linux"

    [[Sundials.download]]
    sha256 = "d6cf7baed8305341dd2d2c52b1833aa60c6f9123b3896ac60c0211e870d12d49"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.2+1/Sundials.v3.1.2.aarch64-linux-musl.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "b3ed88f6b6fc3f3f6b8ad0721dda192db05b243a"
os = "windows"

    [[Sundials.download]]
    sha256 = "19331a41cd8b6f9caa7d8e49332cf92fba171858e696d2bab6cb36be9357cfbc"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.2+1/Sundials.v3.1.2.i686-w64-mingw32.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "4eff2aad07d5eb37e8defc96be42370ab3b518d1"
libc = "musl"
os = "linux"

    [[Sundials.download]]
    sha256 = "622e8240fcb1a474f78bb7d5ef275420b7bc7bc1928ef06a9426e99f70bf4a8a"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.2+1/Sundials.v3.1.2.x86_64-linux-musl.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "41faefd55d1019ff90ec73e2681bab1e0c43cfc7"
libc = "glibc"
os = "linux"

    [[Sundials.download]]
    sha256 = "568057dbb2b5c7ef1ae439753e74e9211ceab58cb4ac6cb78c1f8d12c448c5c3"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.2+1/Sundials.v3.1.2.i686-linux-gnu.tar.gz"
[[Sundials]]
arch = "armv7l"
git-tree-sha1 = "1baa62279576b72733dd5af46c22534d6ca303f3"
libc = "glibc"
os = "linux"

    [[Sundials.download]]
    sha256 = "f5009ff21623dfc6593617f9f95305c0fa8c3aea0e03ca36b0883f53e56c8bd9"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.2+1/Sundials.v3.1.2.armv7l-linux-gnueabihf.tar.gz"
[[Sundials]]
arch = "aarch64"
git-tree-sha1 = "dfc4afa40c0de2353e9b0f0a9740b8033b6849f1"
libc = "glibc"
os = "linux"

    [[Sundials.download]]
    sha256 = "2f58a93517014136f360e031ceab5cb3e6c13ba1fa3cc8270a6c44d9f6de5b1f"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.2+1/Sundials.v3.1.2.aarch64-linux-gnu.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "e6ab86e395592b37073aa1756cd0aa2fdbbd5e4c"
libc = "glibc"
os = "linux"

    [[Sundials.download]]
    sha256 = "ad008fbcc16c1433d8d3e087d5e59e6c149ef0163986ce50f008988856321b59"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.2+1/Sundials.v3.1.2.x86_64-linux-gnu.tar.gz"
[[Sundials]]
arch = "powerpc64le"
git-tree-sha1 = "d6546f3799792d4341346f4843b228f103c6244f"
libc = "glibc"
os = "linux"

    [[Sundials.download]]
    sha256 = "0eb98f07b3efe0553e62c68bd65b141a071f3fa92ba5c5a3cfc240d7ebdb535e"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.2+1/Sundials.v3.1.2.powerpc64le-linux-gnu.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "f7adf93707c31cee667fda0d90a6410a58c4e5b1"
os = "macos"

    [[Sundials.download]]
    sha256 = "5f65dcc8cbee951dc59662e9bcfab6877eceb7b54c64cc62f0feaa5ae7da1b17"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.2+1/Sundials.v3.1.2.x86_64-apple-darwin14.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "48aa63ff03eac7795e195daf2b1918f9b0ab00ae"
os = "freebsd"

    [[Sundials.download]]
    sha256 = "0701702f1a60af901e1524b13f3fd26b363ad3449f7dfd244d07d878ec28a89a"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.2+1/Sundials.v3.1.2.x86_64-unknown-freebsd11.1.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "7363b6eaff5da6166008b622df6547abf30acc98"
libc = "musl"
os = "linux"

    [[Sundials.download]]
    sha256 = "cd0c9a640f89b3b5f8272e2dc3ee538a42bb58f72d194ee70fd90448afd4996a"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.2+1/Sundials.v3.1.2.i686-linux-musl.tar.gz"
[[Sundials]]
arch = "armv7l"
git-tree-sha1 = "5fa141bafe170baa49a117c7755f684f8be7bd9a"
libc = "musl"
os = "linux"

    [[Sundials.download]]
    sha256 = "5fd2be1af519d37039458d68f01311be458724774422a64ff3d9c1f34005c6a4"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.2+1/Sundials.v3.1.2.armv7l-linux-musleabihf.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "74854d8da5e8e8eb2ef5b074c34d3c8085b95043"
os = "windows"

    [[Sundials.download]]
    sha256 = "fe3465de8701359bb14ec64d3a8f5e3b4c45321f236d945c5a31b2f572c758d0"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.2+1/Sundials.v3.1.2.x86_64-w64-mingw32.tar.gz"
