[[Sundials]]
arch = "aarch64"
git-tree-sha1 = "edb1981166923b8ee8edb0e25d9a4a5302e0e8d8"
libc = "musl"
os = "linux"

    [[Sundials.download]]
    sha256 = "3b3337e4fb85b2b59f789abce08f89de384d87f6d200d98d29424c1eaab13e69"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.1+2/Sundials.v3.1.1.aarch64-linux-musl.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "f55fca1a6b90c5791e7cc0543a320dcf969d7395"
os = "windows"

    [[Sundials.download]]
    sha256 = "0bd319fa133b920640cd649dd06e42549105d320d628e65bfa805a02e565a0ac"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.1+2/Sundials.v3.1.1.i686-w64-mingw32.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "6bdaa1ec7f93c6ee167199ec97ea5291e3aa3ea6"
libc = "musl"
os = "linux"

    [[Sundials.download]]
    sha256 = "6f103f4da4480bd1d2cc5e39a95297565b36c7b90b4e40a4f4d01f1686ed2784"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.1+2/Sundials.v3.1.1.x86_64-linux-musl.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "a6551766434a7f8ed0f329ff1ae3a6bc88381c61"
libc = "glibc"
os = "linux"

    [[Sundials.download]]
    sha256 = "29d7937c0a27a58ebc1a8a614aaa92330154f5b690ef2fb39332be0122d7fa7f"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.1+2/Sundials.v3.1.1.i686-linux-gnu.tar.gz"
[[Sundials]]
arch = "armv7l"
git-tree-sha1 = "5c76fadfb14f402b5ced223f0e7c73d4f60ce7e8"
libc = "glibc"
os = "linux"

    [[Sundials.download]]
    sha256 = "1650555ea04dad1645ce538ef0d461f8d94ee3642d5e7189818ba9a860abc781"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.1+2/Sundials.v3.1.1.armv7l-linux-gnueabihf.tar.gz"
[[Sundials]]
arch = "aarch64"
git-tree-sha1 = "dcd1e9e973e08aeacb9da1913b008df6aad59728"
libc = "glibc"
os = "linux"

    [[Sundials.download]]
    sha256 = "2f2359eee98ae002f0eacdacfcff97247fe17603811ca54e9fbe873b5b3102ae"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.1+2/Sundials.v3.1.1.aarch64-linux-gnu.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "87b1d5cd11bd3b8ef3e1a93311c9efc0c8507b81"
libc = "glibc"
os = "linux"

    [[Sundials.download]]
    sha256 = "fc568e49667619e4d1f3b26e31511298f4c5447f3ee9a438227cfdbce9daeb9e"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.1+2/Sundials.v3.1.1.x86_64-linux-gnu.tar.gz"
[[Sundials]]
arch = "powerpc64le"
git-tree-sha1 = "9933ab877c7dc54c8ee5f16acbc230087b169fd7"
libc = "glibc"
os = "linux"

    [[Sundials.download]]
    sha256 = "79b961a667d2fa85e2777ed2ad14d42f0eab75bb8ebeef03cc6d638b0bb3751b"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.1+2/Sundials.v3.1.1.powerpc64le-linux-gnu.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "32ab2e9f532e00636cd84b52ca4cffd73b026600"
os = "macos"

    [[Sundials.download]]
    sha256 = "4b7417b73407a2c0a12001863e367d58a27a90281d50d2e45bcdc651c76ae226"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.1+2/Sundials.v3.1.1.x86_64-apple-darwin14.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "40761cef1940312b1df61a41a609df5941676c1a"
os = "freebsd"

    [[Sundials.download]]
    sha256 = "9bd3783ec48e12a3c04060a24c5f714ec6b02da2ccaff0580048407ec18da2ee"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.1+2/Sundials.v3.1.1.x86_64-unknown-freebsd11.1.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "562b358c924e5a4b2879fd35e1da0d476a6ce221"
libc = "musl"
os = "linux"

    [[Sundials.download]]
    sha256 = "21b30279a8220faca7032610b81d573d5d91d6fdc75637bab76cb5ccdc028122"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.1+2/Sundials.v3.1.1.i686-linux-musl.tar.gz"
[[Sundials]]
arch = "armv7l"
git-tree-sha1 = "f9771e32830c7b76f618c878351800b20acab83a"
libc = "musl"
os = "linux"

    [[Sundials.download]]
    sha256 = "27845c37dd6791f0e837c34fec61c7337e5505f1ecc2d3cf683899c212a1be13"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.1+2/Sundials.v3.1.1.armv7l-linux-musleabihf.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "e4976c00dcf23caf573ebe4433d2b39638bf6920"
os = "windows"

    [[Sundials.download]]
    sha256 = "d1f9a6a7c5e37a02ac1d7ebd4c6cfd0528c99ecc3ba112bdae53df5f452ff464"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.1+2/Sundials.v3.1.1.x86_64-w64-mingw32.tar.gz"
