[[Sundials]]
arch = "aarch64"
git-tree-sha1 = "f4bc37a4672090c93c20b8cd07984eeb3f7d20b6"
libc = "musl"
os = "linux"

    [[Sundials.download]]
    sha256 = "8640999343c725bfa8ee42b5fb230eed0f3ad7a2fe08b2f746a57325f82c3a14"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.2+0/Sundials.v3.1.2.aarch64-linux-musl.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "523c6fbdb5b976a516517bf1108cd5aa96b9d877"
os = "windows"

    [[Sundials.download]]
    sha256 = "872f0d81cb476f3061697e04310a6a491d63679f30815176e00b67a6773d3e58"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.2+0/Sundials.v3.1.2.i686-w64-mingw32.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "f4afd83b19603a4b29c0f40ff037d290cae9804c"
libc = "musl"
os = "linux"

    [[Sundials.download]]
    sha256 = "e716e8ec30dea92306e2da5165f0f5f11ee3198789463e34bd24015b1650eec9"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.2+0/Sundials.v3.1.2.x86_64-linux-musl.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "167f71904ff806e3836bccd024571e1e31bc126b"
libc = "glibc"
os = "linux"

    [[Sundials.download]]
    sha256 = "54e3591a93314ff876aa64bbcd475fa2b6b92dbb2d78f462fe35e334b722ae29"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.2+0/Sundials.v3.1.2.i686-linux-gnu.tar.gz"
[[Sundials]]
arch = "armv7l"
git-tree-sha1 = "f57be0f7b65ea918b23f087710191dd30ba7eabd"
libc = "glibc"
os = "linux"

    [[Sundials.download]]
    sha256 = "3549f13abb7e279bcd341c1c10d5ee8c500eaa4ffb5e250c9dce4acc0110f8a7"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.2+0/Sundials.v3.1.2.armv7l-linux-gnueabihf.tar.gz"
[[Sundials]]
arch = "aarch64"
git-tree-sha1 = "36880006f905ed165212a30b464d08bdb1c6daef"
libc = "glibc"
os = "linux"

    [[Sundials.download]]
    sha256 = "1b0abe140ad34763116b28e0fdec8b46611f5161f1886c63cf7ecd3ea8b7a3f5"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.2+0/Sundials.v3.1.2.aarch64-linux-gnu.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "fc02eeb462f983547ce8d43c7518979daadb1910"
libc = "glibc"
os = "linux"

    [[Sundials.download]]
    sha256 = "575c86f8ff38f7ec5ad31c62f5bde843fe1bf935a370a080fff94d53390ff38a"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.2+0/Sundials.v3.1.2.x86_64-linux-gnu.tar.gz"
[[Sundials]]
arch = "powerpc64le"
git-tree-sha1 = "117d65e694b6017b9a5450db875550ed004e288c"
libc = "glibc"
os = "linux"

    [[Sundials.download]]
    sha256 = "9dc8fd3858316a096a8a8399c8660f4ba2ee20ca77458ad7336a74bf65aa0547"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.2+0/Sundials.v3.1.2.powerpc64le-linux-gnu.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "bd7cd645828b7f5464477fc50ca723306107fcc4"
os = "macos"

    [[Sundials.download]]
    sha256 = "842765322d8cbfdafecc740e8e46cb07548a4a39d4f7084438bad1b21761b8d1"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.2+0/Sundials.v3.1.2.x86_64-apple-darwin14.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "297b7b7dbd126b3688922ed6687ce3c479cb0879"
os = "freebsd"

    [[Sundials.download]]
    sha256 = "19699e4f016fc73c0b54df291108dd8324a1873e627ed5dddab0c1af01ab7496"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.2+0/Sundials.v3.1.2.x86_64-unknown-freebsd11.1.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "a9fa76486a7808f8a4915961ee205cb7612c2b04"
libc = "musl"
os = "linux"

    [[Sundials.download]]
    sha256 = "a7714417b4abbbf3e107893444aed8313c615d892867153510dcd919a27a4379"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.2+0/Sundials.v3.1.2.i686-linux-musl.tar.gz"
[[Sundials]]
arch = "armv7l"
git-tree-sha1 = "4a2b731b471edfd8af79e7bb460c51ba70267a2b"
libc = "musl"
os = "linux"

    [[Sundials.download]]
    sha256 = "a60759bc9087accc76a82620058e5cd479928ff2297cea06f0b897275efb3513"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.2+0/Sundials.v3.1.2.armv7l-linux-musleabihf.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "f9b9a2eae8bd22801ece8177a1621bd53851b30a"
os = "windows"

    [[Sundials.download]]
    sha256 = "044e1c4c85fe0c832886d84f0afccce7cde4e9a931c70809f9c45aa19296c2ec"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.2+0/Sundials.v3.1.2.x86_64-w64-mingw32.tar.gz"
