[[Sundials]]
arch = "i686"
git-tree-sha1 = "e3881deef928ffddce9954790661d09c73b9ca48"
libc = "glibc"
os = "linux"

    [[Sundials.download]]
    sha256 = "dcfc9e6fb2b926689a5283c9c591bb8221e12c4e292f7501d0eab8559dcb2411"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.1+1/Sundials.v3.1.1.i686-linux-gnu.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "0e424a541e9f7166832674f42979c19e416513b7"
libc = "musl"
os = "linux"

    [[Sundials.download]]
    sha256 = "310f7ae6246b7e21b9b029b16653a2e2f578092463036342c2f2b1a462e3d23e"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.1+1/Sundials.v3.1.1.i686-linux-musl.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "90d36e16996864fa53d834814e6d6edc545c4882"
os = "macos"

    [[Sundials.download]]
    sha256 = "beed843c30044bb9fa5d9b13de1d20126fe2e1df7433420795bacfeeda4f6e80"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.1+1/Sundials.v3.1.1.x86_64-apple-darwin14.tar.gz"
[[Sundials]]
arch = "powerpc64le"
git-tree-sha1 = "91f4cd378669e887a07fbce96911699b7e8017ba"
libc = "glibc"
os = "linux"

    [[Sundials.download]]
    sha256 = "b989beb1b8db2748ff05051cf4553e794d56eb16d40732a1b78bcb21dd04d713"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.1+1/Sundials.v3.1.1.powerpc64le-linux-gnu.tar.gz"
[[Sundials]]
arch = "aarch64"
git-tree-sha1 = "eda47242c9fb621b52c43e5b49250a227432f477"
libc = "glibc"
os = "linux"

    [[Sundials.download]]
    sha256 = "368dbbee6e6f2f51ad696ecf2550505db1594eac92b7f8367b47b31d6a27b65a"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.1+1/Sundials.v3.1.1.aarch64-linux-gnu.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "b6da88a760373d4e83b999bfcd76ef1464ea1611"
libc = "musl"
os = "linux"

    [[Sundials.download]]
    sha256 = "c4174fa1c16b9e61374ac4ee6be470d61c66971ed482cf2f8706307e78192ce0"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.1+1/Sundials.v3.1.1.x86_64-linux-musl.tar.gz"
[[Sundials]]
arch = "aarch64"
git-tree-sha1 = "a8030276b3e711741cac18c74debeba0333a0364"
libc = "musl"
os = "linux"

    [[Sundials.download]]
    sha256 = "f2e9b5b389fe331f9c2b13b58193b4f7c72778f1c0e44a81687c11e8963513f6"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.1+1/Sundials.v3.1.1.aarch64-linux-musl.tar.gz"
[[Sundials]]
arch = "armv7l"
git-tree-sha1 = "55a3cc12100fb0f178e0adbb14ca68ce8f60dc9d"
libc = "musl"
os = "linux"

    [[Sundials.download]]
    sha256 = "29a3e69eb89f087cd999e35c1c02626c4751c765e8be404517d1ab89b87b8f3e"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.1+1/Sundials.v3.1.1.arm-linux-musleabihf.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "3876440236270698071d23741da2653e232477f6"
os = "windows"

    [[Sundials.download]]
    sha256 = "abaeebea777400772b95ec7e5e9e7a59b3aa0f961aab8c8e0618058d8f1d0f38"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.1+1/Sundials.v3.1.1.i686-w64-mingw32.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "73ec06b6d05a857eced1cb9a57524585c242a97e"
os = "freebsd"

    [[Sundials.download]]
    sha256 = "5b4a59b10d8b3854a47215e5974aaf9b2ae21ae4ed741670e041876d5608ac9a"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.1+1/Sundials.v3.1.1.x86_64-unknown-freebsd11.1.tar.gz"
[[Sundials]]
arch = "armv7l"
git-tree-sha1 = "24f8a2a793d9b35572460b8c5c5a5ae7bbfedc43"
libc = "glibc"
os = "linux"

    [[Sundials.download]]
    sha256 = "cd9781715f2b82fa3660d38e93d3a1f829e8614124db4de0b23dfdb986016397"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.1+1/Sundials.v3.1.1.arm-linux-gnueabihf.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "702859327f8299772ceafed578ec1b81cd1bd087"
libc = "glibc"
os = "linux"

    [[Sundials.download]]
    sha256 = "51815ba457ddf8904b99d20168fb153c4fc7513e73978fe49e80df444972e2ca"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.1+1/Sundials.v3.1.1.x86_64-linux-gnu.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "a7108b6b8e6331046b14a71b813784de6b390ea5"
os = "windows"

    [[Sundials.download]]
    sha256 = "59401ae3d9eaf7a0f78e6bb4615389e3b6ce0e2e69f20cbe236077dc917cf040"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.1+1/Sundials.v3.1.1.x86_64-w64-mingw32.tar.gz"
