[[Sundials]]
arch = "aarch64"
git-tree-sha1 = "b385bd256032daea42c43dd2f180892510759b42"
libgfortran_version = "5.0.0"
os = "macos"

    [[Sundials.download]]
    sha256 = "d478161c3f9ec75a04a4fa18f6283a48c79e0a1e8b9235e3cff2c6120bde4847"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.6.0+0/Sundials.v6.6.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[Sundials]]
arch = "aarch64"
git-tree-sha1 = "0c9c8d4208df240ec3ab41dd7d7a15d3327f9a7d"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "8b4c7bafa4f97595431feac336204aef8b8a0e5d85d0f88bc3fd084e08f322e2"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.6.0+0/Sundials.v6.6.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[Sundials]]
arch = "aarch64"
git-tree-sha1 = "854ea478ba12b0bd7a926c03420105f5433a5cef"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "834fa4739e6808bfb410ae9d06e78831874c87c46e04532cf1de0d1efaf5da5e"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.6.0+0/Sundials.v6.6.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[Sundials]]
arch = "aarch64"
git-tree-sha1 = "ddfe2344bed431fea8102318aed839a4e0da8a11"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "8052a83d2ea045a1e7addd37193873da8203abbfd16c16142e9c099b83554f54"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.6.0+0/Sundials.v6.6.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[Sundials]]
arch = "aarch64"
git-tree-sha1 = "7faf0a083560a9e0e40aa0892b0c71c9e269f42d"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "fa55d99b8d6fbd5912d560ed8f933caade7ddf836930d9944371cdfee31fdf26"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.6.0+0/Sundials.v6.6.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[Sundials]]
arch = "aarch64"
git-tree-sha1 = "6be01580c42c5d4bea0a3fe52c74b66402705457"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "62b1aa15a156b057dadcda86eec2126641e838d69243c4b003cff5c2a25debc9"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.6.0+0/Sundials.v6.6.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[Sundials]]
arch = "aarch64"
git-tree-sha1 = "086e044f9da6b468e12127b7f6c4af0fa1ead2a2"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "f4c96352565620387f02663bfcfa5fc3ae4d979d91d9899025407103cd47cbec"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.6.0+0/Sundials.v6.6.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[Sundials]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ce454b4873a2edc41319a7f68e64cc106a7de45b"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "407fa9a770e77958a113d68a019a0738b9d84116d290c869bd380e946d22ee1d"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.6.0+0/Sundials.v6.6.0.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[Sundials]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5cec5fd199e2910dd2bc1edd94674a212d0bf5fe"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "042b39b63826427b91ceb36d053e51f8955470bfe9ee2ac8dafd71ee3c80c207"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.6.0+0/Sundials.v6.6.0.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[Sundials]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0981ba590e48f97681e6593e17d6b8c3148365e6"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "40b551f1156409584d49c07e863e94f13d7e8e36a11c6002424921ee3bc8ba1e"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.6.0+0/Sundials.v6.6.0.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[Sundials]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "22557822ffc5ccb85093779122dc522a3f89f05a"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "6f3ae746f3b9d0109d3cf3e7b34abaaa9221ff6a7266eb2be29e3b6353507f2a"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.6.0+0/Sundials.v6.6.0.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[Sundials]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5b400bc201b88eb4756a5230792808eb706271dd"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "8e097d82abb18e0f7e3f12c6564bbc806b9a57b28d9edbcc6466f3edc22b5925"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.6.0+0/Sundials.v6.6.0.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[Sundials]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "371509b387fd82ab7fcaf0c8916b080e3faa855f"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "bd3a025662cf075350bb777ef4605e1f5888d5ae79b57358ff221190cb7104fe"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.6.0+0/Sundials.v6.6.0.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[Sundials]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "41c2b885bc67c1fe1bc647b834b84097af67f399"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "45b629168f3c70117244c90fff26cdf683199491fbd324ca552cb8783956aa57"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.6.0+0/Sundials.v6.6.0.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[Sundials]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "755e0ab7e59da3662340bc0c22b649e27a260236"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "1eeefa99d36ba1e15f4d21a811cd36567c7eb6199f034c457d3f69b476fa19da"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.6.0+0/Sundials.v6.6.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[Sundials]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "07d90b1768ba1204fea52f705feec8ec14c882a4"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "7f0ff2102971c411575be2a2357f6967dcaad5d3badde59d1cc1b539eaaa31dd"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.6.0+0/Sundials.v6.6.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[Sundials]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b7554f3bc3ec1976cc547e096a9a2fa619237859"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "19b09aa18864b0de32a00c31f06e4a2565bbb1c74dfbb85017db44af67328188"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.6.0+0/Sundials.v6.6.0.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[Sundials]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "31f10bce96591933b3bcdf7600719921119288fd"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "622becc4194cf27cee3883bd1b6d6f73361431f6b2a2b90c5a5a4d704c00cb73"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.6.0+0/Sundials.v6.6.0.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[Sundials]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "77621a2b05714397f94b394e63aba1144ca2d07d"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "8a15ae3d67c4559626fd5606638810610fe815394cd791f028a7e6a801208302"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.6.0+0/Sundials.v6.6.0.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "da9312d00caa4e1095204f8df9f90ba41cb189f6"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "b5279c5b08da9c5abbad41bedd35cb1a9d3f68d7266af2f0615b1df28bf5ad89"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.6.0+0/Sundials.v6.6.0.i686-linux-gnu-libgfortran3.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "fa24928f8d70558c6b98e886b2f9ff20421a0dad"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "18124c9897228d9ae68ab91cc2c2e7b3244b79e7996613a185f9c5ba85d3fd7e"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.6.0+0/Sundials.v6.6.0.i686-linux-gnu-libgfortran4.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "5dd0c7c88a66f8a765ada200e3a970f192181b47"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "298140c7cfd85d6f68714635bb24f1f7057e1793534f623e658e0a6bff75f5eb"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.6.0+0/Sundials.v6.6.0.i686-linux-gnu-libgfortran5.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "12e3342e10582622a4b2fab827945b4c74e88c76"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "d06f1fcb1573cc29333dbe13009abf6d45a99695a0f2393d394c63a2671a6580"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.6.0+0/Sundials.v6.6.0.i686-linux-musl-libgfortran3.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "2b69136ed22a81702a5772524a31d3f96e7eeaca"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "2b2cb4244b871ac07bd8dc5edf23c1cbe5a78913b5729270c8071030d2fc2ccf"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.6.0+0/Sundials.v6.6.0.i686-linux-musl-libgfortran4.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "70d898fbb5bc6764fe83bc79949580a3a6eb2ce4"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "685d1b571b7b7e9e3a5437ad34b17069e0bf2d7931203166b4abe5d3e831ee96"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.6.0+0/Sundials.v6.6.0.i686-linux-musl-libgfortran5.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "40864afec3ab1103e966b130ae62c2453d49f4a9"
libgfortran_version = "3.0.0"
os = "windows"

    [[Sundials.download]]
    sha256 = "0c3ab3074c512085acdb085acc73135e715a2e42e258627b57bf0a9f3dcc5b2a"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.6.0+0/Sundials.v6.6.0.i686-w64-mingw32-libgfortran3.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "5d57bb62cd75559b17a305660235fe89b2c3e181"
libgfortran_version = "4.0.0"
os = "windows"

    [[Sundials.download]]
    sha256 = "7650bd3cd41e656adc355dcf9b8a16dd4ea70b0b43415e477c796ef21d9c56f7"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.6.0+0/Sundials.v6.6.0.i686-w64-mingw32-libgfortran4.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "04b85bafc59c1640df0b6987a2171dee8e0becbc"
libgfortran_version = "5.0.0"
os = "windows"

    [[Sundials.download]]
    sha256 = "07bfd481d588c1602af79527bdab9358b269d8a5abbb3a6a6326a7e3afdf412d"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.6.0+0/Sundials.v6.6.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[Sundials]]
arch = "powerpc64le"
git-tree-sha1 = "7140880eca7e8cfeb9c57bd8345f030a0f42e9c9"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "24be242ab07c06894c916465a664cc14d6fcc676fec0b2bc8df7f76d364cff9e"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.6.0+0/Sundials.v6.6.0.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[Sundials]]
arch = "powerpc64le"
git-tree-sha1 = "ecc648baa662725cf5bc83319bbdeddc41bcf670"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "6641be010e047acf82cf77ee9b3303741371f605e372d5454396fd88155da7da"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.6.0+0/Sundials.v6.6.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[Sundials]]
arch = "powerpc64le"
git-tree-sha1 = "5148c2f797982ad3d4bb708599d4e9e38f8816e8"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "c6bf9c6425fb1b477b6ed6a099f139d3d906f193a3f8ab44c9e81c4d743dde5d"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.6.0+0/Sundials.v6.6.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "bb20dd492afabbbfbff72f427b83bea660bfb562"
libgfortran_version = "3.0.0"
os = "macos"

    [[Sundials.download]]
    sha256 = "f8f4caab844fd149a3fbb4e315208fc7b2bcaa9ff87637da1fe754a33c507156"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.6.0+0/Sundials.v6.6.0.x86_64-apple-darwin-libgfortran3.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "bb20dd492afabbbfbff72f427b83bea660bfb562"
libgfortran_version = "4.0.0"
os = "macos"

    [[Sundials.download]]
    sha256 = "f8f4caab844fd149a3fbb4e315208fc7b2bcaa9ff87637da1fe754a33c507156"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.6.0+0/Sundials.v6.6.0.x86_64-apple-darwin-libgfortran4.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "bb20dd492afabbbfbff72f427b83bea660bfb562"
libgfortran_version = "5.0.0"
os = "macos"

    [[Sundials.download]]
    sha256 = "f8f4caab844fd149a3fbb4e315208fc7b2bcaa9ff87637da1fe754a33c507156"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.6.0+0/Sundials.v6.6.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "cbd3b2042b7b223e7b000d1e2f2fbbc20d3f1945"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "6e126b0a9796d7303d188ca9cd60f9096295b8ce223eb33d20d4d9aeb7139854"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.6.0+0/Sundials.v6.6.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "9606303ab5686b230ec344b3607af861f2acdfea"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "e0698f2b6677050c4ac970da45628bab365a37ec4df47450d420a03fbd969442"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.6.0+0/Sundials.v6.6.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "782a51ae8551491a4a580b0a0bbd94c25a58e62b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "8850ca7dd3c348085d281ffa848e453897c8be750f178f62a6b6d99e8e2c65e1"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.6.0+0/Sundials.v6.6.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "fcf23042f49100433b282664e9ee4db5256869b9"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "58365a1ce28b29bc43eaaede452ddddc224f29f89ed07a16be941518de38f4be"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.6.0+0/Sundials.v6.6.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "8922031972c4ecb114a741840e4d9454d5fffedb"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "644e43b569bd2673f6edd7f491b80c3c9fc76a47d686604b3774327f55162ea4"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.6.0+0/Sundials.v6.6.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "2a9f6498c6f52bfdebc873a82d18467cbc2a0ca5"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "843d774db95fbde2c9061d90e701756fc39d03ee9964a3962361ed4354f31372"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.6.0+0/Sundials.v6.6.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "d91d408072eb92984b772d17d3922ccec0bf8ba0"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[Sundials.download]]
    sha256 = "3627bcea539a4f372f6905ad4e1f4b9a42562de28ee67a53d1762b32c44c8f5e"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.6.0+0/Sundials.v6.6.0.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "75c234f89db8c35da68861d11ef29560757cac19"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[Sundials.download]]
    sha256 = "d2297ce7ea662dc39078ffb89032cd47f23bbcced46e3ae7564124cba7e4cf26"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.6.0+0/Sundials.v6.6.0.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "cacf1e0fb84ea8a79d5848c170a1791346c470ca"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Sundials.download]]
    sha256 = "7051f6ae916ea71131ceecba1b38baabbd6b183e08e24277ecd8dbbcd80637d7"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.6.0+0/Sundials.v6.6.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "ee43680b7494d5043103e4f0eeeebda96f99d617"
libgfortran_version = "3.0.0"
os = "windows"

    [[Sundials.download]]
    sha256 = "9000ce3ed9626f784d2d2c3f8abc7c78cfeb29be5d1687bcdd70e7c057459938"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.6.0+0/Sundials.v6.6.0.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "aba4fdd7b8667137d110ce53c8bc5a736819d85f"
libgfortran_version = "4.0.0"
os = "windows"

    [[Sundials.download]]
    sha256 = "f0dd483ba16c64b99a2dbc9bba3065ce75365a6fd590ed7ed8823b23798307c8"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.6.0+0/Sundials.v6.6.0.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "ef1ed86248872d6b80e7ae8116a334c4ecfa6237"
libgfortran_version = "5.0.0"
os = "windows"

    [[Sundials.download]]
    sha256 = "d84385806a4f45739f7e9ac365d7fc0103bb27c2d8fe7b4fb8c409054c5e0055"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.6.0+0/Sundials.v6.6.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
