[[Sundials]]
arch = "aarch64"
git-tree-sha1 = "74ccdee711fd314de4439efee9870f9d30aceab6"
libgfortran_version = "5.0.0"
os = "macos"

    [[Sundials.download]]
    sha256 = "334b9b0fa595a32a5e97fc2c8389cbdeb8615a852ffb9c9212550a883855a2d3"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v7.4.0+1/Sundials.v7.4.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[Sundials]]
arch = "aarch64"
git-tree-sha1 = "146b57ca2afdf76c4d3f067f535891e4c0b27206"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "00aa7246fccac261d82cab7d9050b6b5977096d73c8b231fe8ef7ee6a416c8fe"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v7.4.0+1/Sundials.v7.4.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[Sundials]]
arch = "aarch64"
git-tree-sha1 = "13144189c12bc7100528c22f9bed513194ab7ed0"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "bf693c75f6c2d0b42cb3db1d560f68b65fc131f7fd36835532987d7544974c27"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v7.4.0+1/Sundials.v7.4.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[Sundials]]
arch = "aarch64"
git-tree-sha1 = "78af0c0c024634b1f612c81aa0c936d2995b8fcd"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "686cbccfd7ec16f9f14917a1ed7fb48a94f38daff7bca4136613edc444ccea95"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v7.4.0+1/Sundials.v7.4.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[Sundials]]
arch = "aarch64"
git-tree-sha1 = "fcffb31770e6613fd3d6fd4275332369df1c4960"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "c5cf762c4ae2a2e8fba391bc1bac208048b931e2ff8a8066756896d8b25d1210"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v7.4.0+1/Sundials.v7.4.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[Sundials]]
arch = "aarch64"
git-tree-sha1 = "ed2bee45333445269ebe127a16ba9accb76e810a"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "c78f0bfdfadafcb3a02916d3ac7a1233b45b588f851fa6299caded8770c49151"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v7.4.0+1/Sundials.v7.4.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[Sundials]]
arch = "aarch64"
git-tree-sha1 = "6f8733215e520851cc541509193d741b25a8abfc"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "849dc9f532d9ad3dd6ed701f800dbf5e4888454fed0439bf93612e4d090f8791"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v7.4.0+1/Sundials.v7.4.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[Sundials]]
arch = "aarch64"
git-tree-sha1 = "dba4724a36d33ec9fb7fc99bbd7edac73bd3a73b"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Sundials.download]]
    sha256 = "7d5f220f5b760ba7d731a33d4669e70b29bfa43498b7ee7c97a2d264911645bb"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v7.4.0+1/Sundials.v7.4.0.aarch64-unknown-freebsd-libgfortran5.tar.gz"
[[Sundials]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7dc82a069a9bf55776473837f85d7db88fd1764c"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "9ca8e9d1fadef032be0bf47bc45d2734bf887b96fd392e823e43d6443fd72fcb"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v7.4.0+1/Sundials.v7.4.0.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[Sundials]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "dac35007dbc9b1fc7685846b8e4785583e4a84a5"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "bf53262ecc15d24453d0c3292ae93d747120d0eced9b263402bd1506991a2eef"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v7.4.0+1/Sundials.v7.4.0.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[Sundials]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7773d0365039b7643b404cf5b7654fa1b8b94a0a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "a17bd9cd4019d25c7be9b018d0b5483b49eae59d6cc8a9b676afda88eeffb78d"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v7.4.0+1/Sundials.v7.4.0.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[Sundials]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3a1f3b67140e3bf34e4941107a9f4658fd89df36"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "99b255f2acea2d1351d1af4cb20d687581e9c2b9c84299a600cf9a98dc5ffffe"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v7.4.0+1/Sundials.v7.4.0.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[Sundials]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ad50157d0522d3b1a55b4f52c120b105cb61c5e5"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "e84d8a7f465131ec8846057dddf74e84b9f6922c5ad29bb2291ced61148d0f77"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v7.4.0+1/Sundials.v7.4.0.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[Sundials]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e6e45ab11af0327e5349f9fdb69a66edf672dcf5"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "c80ea4421d95c8535507615d2f0b4d47893a62fd4b9f5f399c7fe2c7964c3d1f"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v7.4.0+1/Sundials.v7.4.0.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[Sundials]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "555ba90570fcd63215ae2d0c3eee7f59b543cc98"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "ab4b51c2d7d5467ec24a70df17de74d4a2269545f57accc92e342cd1140a286c"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v7.4.0+1/Sundials.v7.4.0.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[Sundials]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "36410531f7ff5c57be4e1cfd34f81be9c3203fa6"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "6fc418ea57cca278dd82286b7253d1a412691a5f29846548407ce8adfc572181"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v7.4.0+1/Sundials.v7.4.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[Sundials]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1deea65dd6cb710c1ebf1841d639c9d5d7aecee9"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "b4a619b2a933870c6b14f97d8e674bdb2e5c8d2c26c7a5e4488ac8e45f654ba9"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v7.4.0+1/Sundials.v7.4.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[Sundials]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "38adda6876cf9c59c576008b98258f8dc6d366c0"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "0e40d433a6324a9d31784fb469e1ad240ebe1e23f49dec8b495c88b0c40d216c"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v7.4.0+1/Sundials.v7.4.0.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[Sundials]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "413ae0e1cdabb7eb21ac8fce92cd32d8f93d4902"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "2af2b5acae708ace262a2cd927d1e5f1c564eed874568c3bf389eac33bcef4b5"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v7.4.0+1/Sundials.v7.4.0.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[Sundials]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "260148fe17edf21dcb412ebad28326f132b11d72"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "e8b955894153d140a2da867321961f5e88207fe07ee5be22410315c81cb409ba"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v7.4.0+1/Sundials.v7.4.0.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "408e1eb895f806e462404f87fba9d2679cf997b4"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "61c12ef534c8295efe4bf275181471f75786b2cad7dd884b30d570bb81f65ade"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v7.4.0+1/Sundials.v7.4.0.i686-linux-gnu-libgfortran3.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "d2e97a3795f6dcabec75a2a8c814a0c6bf897bb7"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "7451d7ec82d80e4f5a3161abcee44ee90149530e777976259dd081436835d340"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v7.4.0+1/Sundials.v7.4.0.i686-linux-gnu-libgfortran4.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "b6239208f951220905d6416ac2dd361478de84ae"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "e6fb5c4e9735c9e82a00c1507a5d021edff8ed0e9554bbd08cc6b37491235398"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v7.4.0+1/Sundials.v7.4.0.i686-linux-gnu-libgfortran5.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "2ba934800c613b234276064a811c5f8b393813e5"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "cf07d5b94ead81a6b4f7cb1cf8a79ebaaa8841893e3cae87d91792ec0b6bace1"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v7.4.0+1/Sundials.v7.4.0.i686-linux-musl-libgfortran3.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "8e0479086d4ceda5959aaa0c24704092768d9e1f"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "97f7de369bee0761ec23ee2227deb8b5b1eb9128e4680579d7906111b7554c3e"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v7.4.0+1/Sundials.v7.4.0.i686-linux-musl-libgfortran4.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "1569acd5296783fad76083a0a4106138582a0120"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "308276e715ed1f7454fe618e5b4a568d22abb1a24ddc767d1b9df4d9a873b0dd"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v7.4.0+1/Sundials.v7.4.0.i686-linux-musl-libgfortran5.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "13240ce627f9524d71ab984e728ff3e912595b4a"
libgfortran_version = "3.0.0"
os = "windows"

    [[Sundials.download]]
    sha256 = "5e1b9064f92f3739f3706515f62137c4ff5d24decf6e5e3582f70cf7fab6e3c5"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v7.4.0+1/Sundials.v7.4.0.i686-w64-mingw32-libgfortran3.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "8d2fb1d25657c3ae6e78439afaf49c70ac4138ba"
libgfortran_version = "4.0.0"
os = "windows"

    [[Sundials.download]]
    sha256 = "f9a73ed07fc04e2742a94c9247661d11cf9628e5f51ff98147bfcdd1ab8014b8"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v7.4.0+1/Sundials.v7.4.0.i686-w64-mingw32-libgfortran4.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "cfd7c3732a2ca7d3026574bcefc04b361a5a834d"
libgfortran_version = "5.0.0"
os = "windows"

    [[Sundials.download]]
    sha256 = "c7cfa87e402bb17a3ec4ef16e79184c4249471fddb2669094b60504a1421bc33"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v7.4.0+1/Sundials.v7.4.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[Sundials]]
arch = "powerpc64le"
git-tree-sha1 = "3a93a828d24eb0b5defa4e31d0cacacac69fb793"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "286ddc4eeddf8337ff730eebb45b1167bb54f6778b482efc6583ae2076c89136"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v7.4.0+1/Sundials.v7.4.0.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[Sundials]]
arch = "powerpc64le"
git-tree-sha1 = "cd536bd8f5e79e9edfbffe83895c9bc964da872f"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "ef486d47eb95cfa6b3b89b8232dc3486a417ede0c640bad24e5a096097f4b503"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v7.4.0+1/Sundials.v7.4.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[Sundials]]
arch = "powerpc64le"
git-tree-sha1 = "ee30ba4ea6baeaf0d68feabd369ba25c0d8d7b52"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "bd80860905ab4e13a4adc20b31400d1e16aa6c2ce8665968bf578c026d098a0d"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v7.4.0+1/Sundials.v7.4.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[Sundials]]
arch = "riscv64"
git-tree-sha1 = "825c12fc43bc27876ec12620e7abeddaf396cbe5"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "ff9b7f4811ac8948cdb5a6004566ee703c6b88f26358d218389c2dca39564766"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v7.4.0+1/Sundials.v7.4.0.riscv64-linux-gnu-libgfortran5.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "5ab9f684e0fa32ceb95ac7553513dc4c49c691ce"
libgfortran_version = "3.0.0"
os = "macos"

    [[Sundials.download]]
    sha256 = "3263d6434cd161a2567527f22b5cb5f2bf57d329c1c921c2ce2dacb50882de5c"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v7.4.0+1/Sundials.v7.4.0.x86_64-apple-darwin-libgfortran3.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "5ab9f684e0fa32ceb95ac7553513dc4c49c691ce"
libgfortran_version = "4.0.0"
os = "macos"

    [[Sundials.download]]
    sha256 = "3263d6434cd161a2567527f22b5cb5f2bf57d329c1c921c2ce2dacb50882de5c"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v7.4.0+1/Sundials.v7.4.0.x86_64-apple-darwin-libgfortran4.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "5ab9f684e0fa32ceb95ac7553513dc4c49c691ce"
libgfortran_version = "5.0.0"
os = "macos"

    [[Sundials.download]]
    sha256 = "3263d6434cd161a2567527f22b5cb5f2bf57d329c1c921c2ce2dacb50882de5c"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v7.4.0+1/Sundials.v7.4.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "452e1c066daa4d60fe5ca90142ab9d4c021e004e"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "019a1c496c8742da44ba41063f5ad441d2eca32cfb6a154f47f40dc042d05bd6"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v7.4.0+1/Sundials.v7.4.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "cbd148247a04a1b35ffafec70f042a7a489b0ed2"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "d8fcd5c627098dfcaa188fb9a63119445cfb6951475aeefd91fc740ee42faa26"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v7.4.0+1/Sundials.v7.4.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "7aeae0c0944c4ac17cd714fce66d8757d6003f69"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "1dbe6d2072f577e490c3e0b11a118a2430a6331c93cc79af86209a560919d06d"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v7.4.0+1/Sundials.v7.4.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "c64fbd04b027c57a5290f53d0643aca5d6986b74"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "7c0dfa35cf0771cbbb729e85c445daa79820e9ad09dc792fdad9cbe2cd26ba01"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v7.4.0+1/Sundials.v7.4.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "28927f7616d86508901bacc076afe5ec5c3ee450"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "ecb5e0a9db37461dbe77738f40f88493f9c6657edf37ad2291f3c2f6ba037a67"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v7.4.0+1/Sundials.v7.4.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "e36709e0e9a19960bb848931f74ecd3c9fbb0e30"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "ade8fb6ab20c98d6fb27ae8b81af2ac8ceb1b1c6d19134253e6fabfc644afe2b"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v7.4.0+1/Sundials.v7.4.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "13296632109a31ade72d826cee4d9e5c631a7e40"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[Sundials.download]]
    sha256 = "048268fbf046a83bd396bbd9d340023132614262d479140b02d633493cc75bbe"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v7.4.0+1/Sundials.v7.4.0.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "13296632109a31ade72d826cee4d9e5c631a7e40"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[Sundials.download]]
    sha256 = "048268fbf046a83bd396bbd9d340023132614262d479140b02d633493cc75bbe"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v7.4.0+1/Sundials.v7.4.0.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "13296632109a31ade72d826cee4d9e5c631a7e40"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Sundials.download]]
    sha256 = "048268fbf046a83bd396bbd9d340023132614262d479140b02d633493cc75bbe"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v7.4.0+1/Sundials.v7.4.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "b57992db9acd3054057dae02656dcecb08ce619b"
libgfortran_version = "3.0.0"
os = "windows"

    [[Sundials.download]]
    sha256 = "b742db6a188fa7cffba27f5faeffb5646563a506d08dddbc2f29e466b0df076c"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v7.4.0+1/Sundials.v7.4.0.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "53c9b70059c656c7a3024dc44941959286e9b2a4"
libgfortran_version = "4.0.0"
os = "windows"

    [[Sundials.download]]
    sha256 = "3a2380e2e2379f37c99e2de5c6ff78c67bef3c12b8d1e18a3bc01731712ee210"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v7.4.0+1/Sundials.v7.4.0.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "2cdeb0ce8bf087c5391b6503c42c448056b2fc3a"
libgfortran_version = "5.0.0"
os = "windows"

    [[Sundials.download]]
    sha256 = "d7e9d66a675426cc00ebfa51bbdcdb2817eb34aaf14b945e47b9e5342bc9c8a5"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v7.4.0+1/Sundials.v7.4.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
