[[Sundials]]
arch = "aarch64"
git-tree-sha1 = "e77e3b55dc17696f07daac9e272e6fd9af38762e"
libc = "glibc"
os = "linux"

    [[Sundials.download]]
    sha256 = "4622d0f245ab81b74ac5fcfcadb38661d99a179834580dd29f9e05851822210c"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.2+2/Sundials.v3.1.2.aarch64-linux-gnu.tar.gz"
[[Sundials]]
arch = "aarch64"
git-tree-sha1 = "3eb11786229399f56586ea7b93ad6737222486c1"
libc = "musl"
os = "linux"

    [[Sundials.download]]
    sha256 = "850abcee5f66a2b501fc273cee884d806f22613a7dddd6ad78b9a1d4122cf07d"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.2+2/Sundials.v3.1.2.aarch64-linux-musl.tar.gz"
[[Sundials]]
arch = "armv7l"
git-tree-sha1 = "6bef65a8b65e269754ef2796538ea73829a4d261"
libc = "glibc"
os = "linux"

    [[Sundials.download]]
    sha256 = "d03ac14baaf105963a5cf1b25b9315535cf27fced966cf11ee9fed8bf2f27830"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.2+2/Sundials.v3.1.2.armv7l-linux-gnueabihf.tar.gz"
[[Sundials]]
arch = "armv7l"
git-tree-sha1 = "2d62e0362dc6408afe2c8b6051a815edda0e9216"
libc = "musl"
os = "linux"

    [[Sundials.download]]
    sha256 = "8dbc24d03af04b7630be3c18ba57f2b7987588c093783f71205d751fc99a42a5"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.2+2/Sundials.v3.1.2.armv7l-linux-musleabihf.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "66af144584a8147769868a2626ce4fdb9d738015"
libc = "glibc"
os = "linux"

    [[Sundials.download]]
    sha256 = "6f34a6a0d595381400ea0ff9f28971af0b5a5c262c7010cd907c4c95a4550a12"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.2+2/Sundials.v3.1.2.i686-linux-gnu.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "acfe59a38071aa89b3afec63df6db4483331d736"
libc = "musl"
os = "linux"

    [[Sundials.download]]
    sha256 = "9e637c0274273faef5453a33630db0f87292957576b7ff24bbc1b86a07bd035c"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.2+2/Sundials.v3.1.2.i686-linux-musl.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "c8614014f0d9f5e480f88aa5933c521b7f6a593d"
os = "windows"

    [[Sundials.download]]
    sha256 = "cae4545e74d339673e69f94fb1560832da84a7110401e29dd6a812ca7d79e477"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.2+2/Sundials.v3.1.2.i686-w64-mingw32.tar.gz"
[[Sundials]]
arch = "powerpc64le"
git-tree-sha1 = "b4ee934dd3188a4f91344011df1fca8b2d5c7400"
libc = "glibc"
os = "linux"

    [[Sundials.download]]
    sha256 = "9ced000833616d05b8e9be2d6f8aed91bd50cb4cc93debb57917862145efe4dc"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.2+2/Sundials.v3.1.2.powerpc64le-linux-gnu.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "9f51603d63186427f3c732a91b68c1ba37528958"
os = "macos"

    [[Sundials.download]]
    sha256 = "3f01dbba9dadc045516189015020a5bf29f2e753be5b80dc7db482e8b86581ce"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.2+2/Sundials.v3.1.2.x86_64-apple-darwin14.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "fedac3e2eccbf49849d767e2ced371ee7f70c5db"
libc = "glibc"
os = "linux"

    [[Sundials.download]]
    sha256 = "f6672448ecf94478ad53bb1f4d26ca8a317710638aa384c23db60c2bf287c8a4"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.2+2/Sundials.v3.1.2.x86_64-linux-gnu.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "08cae1cfb6b2c4adaff059ced5635a0d820d7749"
libc = "musl"
os = "linux"

    [[Sundials.download]]
    sha256 = "cec57d02521c7c4425cd9144ae0edfccf181a794d573bd101bb3fc03aa291e72"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.2+2/Sundials.v3.1.2.x86_64-linux-musl.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "23b63b05aa1fc53d77fd059787dbf5fe6b9b4592"
os = "freebsd"

    [[Sundials.download]]
    sha256 = "d5486fbf107c3e9e0dd50ce235b3acf120038e7f5549a33407a07e56f3dcd5d4"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.2+2/Sundials.v3.1.2.x86_64-unknown-freebsd11.1.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "e3a09bcbfad1e1b99ab79aec03b101d00bb8b77b"
os = "windows"

    [[Sundials.download]]
    sha256 = "4c722caa4efcd020c30390c0eb969a4250d16b65000a41e0d45433175f9318b3"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.2+2/Sundials.v3.1.2.x86_64-w64-mingw32.tar.gz"
