[[Sundials]]
arch = "aarch64"
git-tree-sha1 = "e62d526a7279c8cca55279820167c1b3c2fd104c"
libgfortran_version = "5.0.0"
os = "macos"

    [[Sundials.download]]
    sha256 = "33a39977cbdf4487542e3aafbb594f16f83bbf5114fcd627d90379fa8d20ac0a"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.7.0+0/Sundials.v6.7.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[Sundials]]
arch = "aarch64"
git-tree-sha1 = "f18d5a23aaedcb13ab6efc33893a2a60fa2ce2c1"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "834ce85a792fc56677c650521a36a8fad2274a8bfcb362493d085d65b55dbd33"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.7.0+0/Sundials.v6.7.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[Sundials]]
arch = "aarch64"
git-tree-sha1 = "e4a44a474d0d1dadb6c6a4dba610d0731977bd33"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "d352b297a99b28c0d25bea88759e04d3ebbec9e3ab029ecbef3774aab80e2561"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.7.0+0/Sundials.v6.7.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[Sundials]]
arch = "aarch64"
git-tree-sha1 = "29069d9664b92e2bfe0f3f5e18ab0c4d1bff1517"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "17c98ed7efa492ac3de09d295a99583aade5dcb11a45416325b52556dd43bd6c"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.7.0+0/Sundials.v6.7.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[Sundials]]
arch = "aarch64"
git-tree-sha1 = "3ddf9c1a84a8f78457e8ca151b7748523ea2a28c"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "78f6a1e54659c79fd83236af7d3031b73452a9dc5570ffa7ef342a9076197140"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.7.0+0/Sundials.v6.7.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[Sundials]]
arch = "aarch64"
git-tree-sha1 = "ad718c6de8bde092fb7f4adc796c67427b170b4e"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "7041371981c21bdda1619828b69e73fee97be843922ae47684bae7c9b08817e1"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.7.0+0/Sundials.v6.7.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[Sundials]]
arch = "aarch64"
git-tree-sha1 = "8a4bde75c8b69d4a3bf239687192a905e87c8c55"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "6bd59ed50f83777a13712d4ff9c0422655d3ca008313b55daa03ffd6022f6779"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.7.0+0/Sundials.v6.7.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[Sundials]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1582bdea2b33a9dcd86797fdb67f0762e2b3aefa"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "93e3dd66d9b4c1ea5766cb3125e14be14a99dd4e3c37821ead44ce9720ecefee"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.7.0+0/Sundials.v6.7.0.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[Sundials]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1dbfa1c3e125ad86c44be280c9ab565b78b868aa"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "66bb534f16a2991faa8f393b00ffd28ea11f655f5ec0b5a299425592c5fe4c85"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.7.0+0/Sundials.v6.7.0.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[Sundials]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0c73ce9519a3c7f44030c60fc6a3b9bd8ce722c2"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "361c5a75b0d72b4ab8cf14978ff271e870b35136710587c615a5af7c3e3b8308"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.7.0+0/Sundials.v6.7.0.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[Sundials]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "317c3353ea963ea6d1f22f8fb41125ba9d9d8a86"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "3cafbabf70c1ce27e789a141fde75fe0771e28b04c38e039abc501c686e131e9"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.7.0+0/Sundials.v6.7.0.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[Sundials]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f02e52aaeaf356fc6445abbc427acf0f482f638f"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "1adbaba306cfc6173c79c838c331b78521db869d9f80afdbd8068bf75b7cdc18"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.7.0+0/Sundials.v6.7.0.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[Sundials]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "750894296bddbdf7bef061b8f49a0a059ac4fca7"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "2994f639ae5f3de80631984af2df8a4bfec0b31a0ff5c2613dd6f470ec244402"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.7.0+0/Sundials.v6.7.0.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[Sundials]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "74bffbbc6e811c0d95ce87d80aa2b1998aaf4a13"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "e44d03ba5322a89dc94baec5d3a9b29ef6231ac1c4df8cc9c07586e97bf57df1"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.7.0+0/Sundials.v6.7.0.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[Sundials]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "56a01093be2a5b387f410351dd79d6d4676fc145"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "5d1d68091ac932b36153e7ca1b2424ded9502d592ccab021967c6e2feeea2414"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.7.0+0/Sundials.v6.7.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[Sundials]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "284ce25423a3ccfba822e9de6346d33acc87ab7c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "388fd349535d0ed713c1f314dcc2123070492183c92ba4c789adcb8e23f7fb4e"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.7.0+0/Sundials.v6.7.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[Sundials]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b65152b99e54f9332a6b9201177bb88047c46367"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "544fcae728561f4f241b6df452a8c595b3dc720ba650c40e05180438a7b13bfe"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.7.0+0/Sundials.v6.7.0.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[Sundials]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b6034d3c2ac4268f8c9636ba42abe44857f1dbdf"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "775b41b98f5c43771b5feee37b7ff412f966ab5f8f37e7a26d194238d0fecc4d"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.7.0+0/Sundials.v6.7.0.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[Sundials]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8c0f057aefd675766fad42f0ab73273031fe0d7d"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "e52c20e4e639a6545a6c4c6faae8ac3bfabbe337ce3be1de89729421cef9d8e6"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.7.0+0/Sundials.v6.7.0.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "37532233145eb9f8715abaa54ea466373786f450"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "b720fa8c945ebb06a0022fdea8a444aba4dbc1ec19e1388e67e0f49bb422d7e1"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.7.0+0/Sundials.v6.7.0.i686-linux-gnu-libgfortran3.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "613461d1f4d43a11618b7b013847dc1ee5fe0c85"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "8da01087c3b96f46ca8b23cfd9333a76a1634ca1f9abf87c9605edbc9970a97f"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.7.0+0/Sundials.v6.7.0.i686-linux-gnu-libgfortran4.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "2598057ba429a3a48761591eec08e5010a298538"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "222a58acb17b71da405e4006d60067ed7bf2cce52c1f060e57be881157b7786a"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.7.0+0/Sundials.v6.7.0.i686-linux-gnu-libgfortran5.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "21ce6f038f8456e17500f73ef971f8dc1d46ffab"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "c55395baf0ad6348c601f0bb7253701c1e22724fe8c7d90f0eaa19bb3caa5307"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.7.0+0/Sundials.v6.7.0.i686-linux-musl-libgfortran3.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "4abaa79b17e89250fd77a6b1653726d96628eb9d"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "865387209ac00d603cf95073c186dac2ff679b61d362a606065b19a37d5686f6"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.7.0+0/Sundials.v6.7.0.i686-linux-musl-libgfortran4.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "fc8eb3a06b0845ee3a43dbca03999fa2d27f99b3"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "916aaf54c0b9f3cd54bffc0ecdc9b011b861e65345b5c16181181dc121bb3372"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.7.0+0/Sundials.v6.7.0.i686-linux-musl-libgfortran5.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "0fc54b8556287540c6f8b96317fb8274ac8da8bf"
libgfortran_version = "3.0.0"
os = "windows"

    [[Sundials.download]]
    sha256 = "7f5034c6364008dc5f4e61065b7abe4791429c3e04491a31cbd2cc236af7c729"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.7.0+0/Sundials.v6.7.0.i686-w64-mingw32-libgfortran3.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "287804a29c9f70c69f9e2d782b10c633f31e176b"
libgfortran_version = "4.0.0"
os = "windows"

    [[Sundials.download]]
    sha256 = "88fcbe10321f569efc0e8a982b919697bac7c61843d3a8e29107d771522fe2c4"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.7.0+0/Sundials.v6.7.0.i686-w64-mingw32-libgfortran4.tar.gz"
[[Sundials]]
arch = "i686"
git-tree-sha1 = "24f74fe4075f19cd1660fcbb1c080762ecdb91fb"
libgfortran_version = "5.0.0"
os = "windows"

    [[Sundials.download]]
    sha256 = "0834698b8fb27d7f855f68d55bc286b79db0338a8fadc515ff8a66b8b12db2b6"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.7.0+0/Sundials.v6.7.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[Sundials]]
arch = "powerpc64le"
git-tree-sha1 = "f9ada120a1a885e5b1699af980734265e51ebf10"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "8d1cac26b18a21b835676ac9b814888e384dcb01d02e0126d043adefc037e479"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.7.0+0/Sundials.v6.7.0.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[Sundials]]
arch = "powerpc64le"
git-tree-sha1 = "bb8c0bf5a05257fbfcd51901899132f29df48dc2"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "3ed5b3617367c619498c148b9dcf8ae179bc61a515ea582278ed3b57da9114fe"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.7.0+0/Sundials.v6.7.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[Sundials]]
arch = "powerpc64le"
git-tree-sha1 = "b88c9e245d2fee0c31607fd1a92cd0088e669d3d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "5a5d1b0c04d542f02ccef2f16be2623514aced6a36674b8146862b201029662f"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.7.0+0/Sundials.v6.7.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "23c350064062b265dee55e11ac86a14c44cb2f43"
libgfortran_version = "3.0.0"
os = "macos"

    [[Sundials.download]]
    sha256 = "6c1769edf16416b659c221b152aa684cce84a05392e3e7558df07e6c087758bf"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.7.0+0/Sundials.v6.7.0.x86_64-apple-darwin-libgfortran3.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "23c350064062b265dee55e11ac86a14c44cb2f43"
libgfortran_version = "4.0.0"
os = "macos"

    [[Sundials.download]]
    sha256 = "6c1769edf16416b659c221b152aa684cce84a05392e3e7558df07e6c087758bf"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.7.0+0/Sundials.v6.7.0.x86_64-apple-darwin-libgfortran4.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "23c350064062b265dee55e11ac86a14c44cb2f43"
libgfortran_version = "5.0.0"
os = "macos"

    [[Sundials.download]]
    sha256 = "6c1769edf16416b659c221b152aa684cce84a05392e3e7558df07e6c087758bf"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.7.0+0/Sundials.v6.7.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "d66bdbfa581d1c0ec3e4a998061ba5e0b4368623"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "175bf50a6a8d1664147466c3b5d8d3bc4369897ec3b06b74380f8cfce96683c0"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.7.0+0/Sundials.v6.7.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "53b70baa02d7a37622cbce528385af4507639b16"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "e6c5c987252afe9c94836821d37abac04d43217d10cae5976b4ead04015dfa5e"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.7.0+0/Sundials.v6.7.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "c607f9d59bfc1d46fd6438c0f011941e705a914a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "8cff5594218a4b689ae4a8c50c33dd81c959aac3cdcc960bcb7f5c52951dfb85"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.7.0+0/Sundials.v6.7.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "bc768b44db9f9f43eb92e80249438fd9926257ba"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "60a4d8c30ab1a4aa63fd5fe99d7f0a8f1ea28907af1143016148cd18d72d9175"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.7.0+0/Sundials.v6.7.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "48f5400aaadb85cdc490cdc2496052d2daa5ab0b"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "8b945d5678f1c2935c94a1522c127b2b28d71bfbeeb08d65a336057f3e15e8c3"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.7.0+0/Sundials.v6.7.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "9343c0f7707c0563e0d805027f16fa09c719b7d1"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials.download]]
    sha256 = "36a3a7c031b8327185adb841332e7207d9f7f94247ac1974cec07033c684948d"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.7.0+0/Sundials.v6.7.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "ca611b26aa96bf361b4488e3823a0da059b51639"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[Sundials.download]]
    sha256 = "eea072baf6b6e546afd268ab06d1738d55716afd49713ae1998248ac29a504b0"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.7.0+0/Sundials.v6.7.0.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "ca611b26aa96bf361b4488e3823a0da059b51639"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[Sundials.download]]
    sha256 = "eea072baf6b6e546afd268ab06d1738d55716afd49713ae1998248ac29a504b0"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.7.0+0/Sundials.v6.7.0.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "ca611b26aa96bf361b4488e3823a0da059b51639"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Sundials.download]]
    sha256 = "eea072baf6b6e546afd268ab06d1738d55716afd49713ae1998248ac29a504b0"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.7.0+0/Sundials.v6.7.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "7ae8e60b7150f4125e97583276f9b83bd4d25277"
libgfortran_version = "3.0.0"
os = "windows"

    [[Sundials.download]]
    sha256 = "cdf86c6f9c3a63ebae2c7e96c4a30c8e5a529723cbd7bd67fd2bdae5ee9230d2"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.7.0+0/Sundials.v6.7.0.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "e3719d9b129d38b9c7ea11d40b9b35eb16d69d1b"
libgfortran_version = "4.0.0"
os = "windows"

    [[Sundials.download]]
    sha256 = "17388ed6f1c055eace166ee6a49ef7d2a9b62e66184af7e662b968cea964032c"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.7.0+0/Sundials.v6.7.0.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[Sundials]]
arch = "x86_64"
git-tree-sha1 = "a34a0614ad69bf9c0ddb7f0b7a130ed2545d9b03"
libgfortran_version = "5.0.0"
os = "windows"

    [[Sundials.download]]
    sha256 = "663bd6390cf085a17d49a1e3eb7aa84104a3cb2d96653b8f6d038f6b3d81f694"
    url = "https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v6.7.0+0/Sundials.v6.7.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
