# Autogenerated wrapper script for Sundials_jll for x86_64-w64-mingw32-libgfortran4
export libsundials_arkode, libsundials_cvode, libsundials_cvodes, libsundials_ida, libsundials_idas, libsundials_kinsol, libsundials_nvecmanyvector, libsundials_nvecserial, libsundials_sunlinsolband, libsundials_sunlinsoldense, libsundials_sunlinsolklu, libsundials_sunlinsollapackband, libsundials_sunlinsollapackdense, libsundials_sunlinsolpcg, libsundials_sunlinsolspbcgs, libsundials_sunlinsolspfgmr, libsundials_sunlinsolspgmr, libsundials_sunlinsolsptfqmr, libsundials_sunmatrixband, libsundials_sunmatrixdense, libsundials_sunmatrixsparse, libsundials_sunnonlinsolfixedpoint, libsundials_sunnonlinsolnewton

using CompilerSupportLibraries_jll
using OpenBLAS_jll
using SuiteSparse_jll
JLLWrappers.@generate_wrapper_header("Sundials")
JLLWrappers.@declare_library_product(libsundials_arkode, "libsundials_arkode.dll")
JLLWrappers.@declare_library_product(libsundials_cvode, "libsundials_cvode.dll")
JLLWrappers.@declare_library_product(libsundials_cvodes, "libsundials_cvodes.dll")
JLLWrappers.@declare_library_product(libsundials_ida, "libsundials_ida.dll")
JLLWrappers.@declare_library_product(libsundials_idas, "libsundials_idas.dll")
JLLWrappers.@declare_library_product(libsundials_kinsol, "libsundials_kinsol.dll")
JLLWrappers.@declare_library_product(libsundials_nvecmanyvector, "libsundials_nvecmanyvector.dll")
JLLWrappers.@declare_library_product(libsundials_nvecserial, "libsundials_nvecserial.dll")
JLLWrappers.@declare_library_product(libsundials_sunlinsolband, "libsundials_sunlinsolband.dll")
JLLWrappers.@declare_library_product(libsundials_sunlinsoldense, "libsundials_sunlinsoldense.dll")
JLLWrappers.@declare_library_product(libsundials_sunlinsolklu, "libsundials_sunlinsolklu.dll")
JLLWrappers.@declare_library_product(libsundials_sunlinsollapackband, "libsundials_sunlinsollapackband.dll")
JLLWrappers.@declare_library_product(libsundials_sunlinsollapackdense, "libsundials_sunlinsollapackdense.dll")
JLLWrappers.@declare_library_product(libsundials_sunlinsolpcg, "libsundials_sunlinsolpcg.dll")
JLLWrappers.@declare_library_product(libsundials_sunlinsolspbcgs, "libsundials_sunlinsolspbcgs.dll")
JLLWrappers.@declare_library_product(libsundials_sunlinsolspfgmr, "libsundials_sunlinsolspfgmr.dll")
JLLWrappers.@declare_library_product(libsundials_sunlinsolspgmr, "libsundials_sunlinsolspgmr.dll")
JLLWrappers.@declare_library_product(libsundials_sunlinsolsptfqmr, "libsundials_sunlinsolsptfqmr.dll")
JLLWrappers.@declare_library_product(libsundials_sunmatrixband, "libsundials_sunmatrixband.dll")
JLLWrappers.@declare_library_product(libsundials_sunmatrixdense, "libsundials_sunmatrixdense.dll")
JLLWrappers.@declare_library_product(libsundials_sunmatrixsparse, "libsundials_sunmatrixsparse.dll")
JLLWrappers.@declare_library_product(libsundials_sunnonlinsolfixedpoint, "libsundials_sunnonlinsolfixedpoint.dll")
JLLWrappers.@declare_library_product(libsundials_sunnonlinsolnewton, "libsundials_sunnonlinsolnewton.dll")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, OpenBLAS_jll, SuiteSparse_jll)
    JLLWrappers.@init_library_product(
        libsundials_arkode,
        "bin\\libsundials_arkode.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsundials_cvode,
        "bin\\libsundials_cvode.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsundials_cvodes,
        "bin\\libsundials_cvodes.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsundials_ida,
        "bin\\libsundials_ida.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsundials_idas,
        "bin\\libsundials_idas.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsundials_kinsol,
        "bin\\libsundials_kinsol.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsundials_nvecmanyvector,
        "bin\\libsundials_nvecmanyvector.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsundials_nvecserial,
        "bin\\libsundials_nvecserial.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsundials_sunlinsolband,
        "bin\\libsundials_sunlinsolband.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsundials_sunlinsoldense,
        "bin\\libsundials_sunlinsoldense.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsundials_sunlinsolklu,
        "bin\\libsundials_sunlinsolklu.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsundials_sunlinsollapackband,
        "bin\\libsundials_sunlinsollapackband.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsundials_sunlinsollapackdense,
        "bin\\libsundials_sunlinsollapackdense.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsundials_sunlinsolpcg,
        "bin\\libsundials_sunlinsolpcg.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsundials_sunlinsolspbcgs,
        "bin\\libsundials_sunlinsolspbcgs.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsundials_sunlinsolspfgmr,
        "bin\\libsundials_sunlinsolspfgmr.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsundials_sunlinsolspgmr,
        "bin\\libsundials_sunlinsolspgmr.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsundials_sunlinsolsptfqmr,
        "bin\\libsundials_sunlinsolsptfqmr.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsundials_sunmatrixband,
        "bin\\libsundials_sunmatrixband.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsundials_sunmatrixdense,
        "bin\\libsundials_sunmatrixdense.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsundials_sunmatrixsparse,
        "bin\\libsundials_sunmatrixsparse.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsundials_sunnonlinsolfixedpoint,
        "bin\\libsundials_sunnonlinsolfixedpoint.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsundials_sunnonlinsolnewton,
        "bin\\libsundials_sunnonlinsolnewton.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
